version: '3.8'
services:
    db:
        image: mysql:8.0
        container_name: resume_db
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - dev

    pma:
        image: phpmyadmin:latest
        container_name: resume_pma
        restart: always
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
        networks:
            - dev

    php:
        build:
            context: .
            dockerfile: docker/dev/Dockerfile
        container_name: resume_php
        ports:
            - "8000:80"
        volumes:
            - ./docker/apache/sites-enabled:/etc/apache2/sites-enabled
            - ./:/var/www/html:cached
            #- /var/www/html/vendor
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:
